---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - apprise_config_folder is defined

- name: Copy apprise config
  copy:
    src: "{{ apprise_config_folder }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}"
    owner: ubuntu
    group: ubuntu
    force: true
    mode: 0644
    directory_mode: 0775

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "caronc/{{ application_name }}:latest"
    pull: true
    cleanup: true
    exposed_ports: 8000
    published_ports:
      - "0.0.0.0:9000:8000"  # map the port to the host's 9000 port
    memory: "200MB"
    log_driver: "awslogs"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}:/var/lib/apprise/config"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}"
    env:
      APPRISE_STATEFUL_MODE: "simple"
